name: CI - Expense Service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # ------------------------
      # 1. Linting
      # ------------------------
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install linters
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install golang.org/x/lint/golint@latest

      - name: Run linters
        run: |
          golint ./... || true
          staticcheck ./...

      # ------------------------
      # 2. SAST (Static Analysis with Gosec)
      # ------------------------
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

      # ------------------------
      # 3. SCA (Dependency vulnerability scanning)
      # ------------------------
      - name: Dependency Review (GitHub native)
        uses: actions/dependency-review-action@v4

      - name: Generate SBOM (Syft)
        uses: anchore/syft-action@v0.16.0
        with:
          image: docker.io/minnuantony/expense-service:latest
          format: table

      # ------------------------
      # 4. Docker Build & Push
      # ------------------------
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          IMAGE=minnuantony/expense-service
          SHA_TAG=$IMAGE:sha-${GITHUB_SHA}
          LATEST_TAG=$IMAGE:latest
          docker build -t $SHA_TAG -t $LATEST_TAG .
          docker push $SHA_TAG
          docker push $LATEST_TAG

      # ------------------------
      # 5. Update Deployment Manifest
      # ------------------------
      - name: Update Deployment Manifest
        run: |
          sed -i "s|image: .*|image: minnuantony/expense-service:sha-${GITHUB_SHA}|" ./k8s/deployment.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./k8s/deployment.yaml
          git commit -m "Update expense-service image to sha-${GITHUB_SHA}" || echo "No changes to commit"
          git push
