name: CI - Expense Service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # ------------------------
      # 1. Set up Go & Linters
      # ------------------------
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Download Go dependencies
        run: go mod tidy

      - name: Install linters
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install golang.org/x/lint/golint@latest

      - name: Run linters
        run: |
          golint ./... || true
          staticcheck ./... || true

      # ------------------------
      # 2. SAST (Static Analysis with Gosec)
      # ------------------------
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: -severity=HIGH -confidence=HIGH ./...

      # ------------------------
      # 3. Docker Build (no push yet)
      # ------------------------
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          IMAGE=minnuantony/expense-service
          SHA_TAG=$IMAGE:sha-${GITHUB_SHA}
          LATEST_TAG=$IMAGE:latest
          docker build -t $SHA_TAG -t $LATEST_TAG .
          echo "SHA_TAG=$SHA_TAG" >> $GITHUB_ENV
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      # ------------------------
      # 4. Trivy Scan (before pushing)
      # ------------------------
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.SHA_TAG }}
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '0'   # change to '1' if you want pipeline to fail on vulnerabilities

      # ------------------------
      # 5. Push Docker Images
      # ------------------------
      - name: Push Docker Images
        run: |
          docker push ${{ env.SHA_TAG }}
          docker push ${{ env.LATEST_TAG }}

      # ------------------------
      # 6. Update Deployment Manifest
      # ------------------------
      - name: Update Deployment Manifest
        run: |
          sed -i "s|image: .*|image: minnuantony/expense-service:sha-${GITHUB_SHA}|" ./k8s/deployment.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./k8s/deployment.yaml
          git commit -m "Update expense-service image to sha-${GITHUB_SHA}" || echo "No changes to commit"
          git push
